### ISSUE TITLE
Apply the Python juypter knowledge on the google colab

### ISSUE THREAD

**Issue by habib-19** [sajawalferoze/Saji_miniJob#4]
- [x] read file (it will be read from google drive)
- [x] draw data graphs
- [x] What is histogram
- [x] Draw histogram

**Comment by sajawalferoze** [comment]
i know how to read a file from any directory within my computer but for google drive I dont know what is that API and how to deal with it
but I know a little about .json file
So please help me with that.

**Comment by habib-19** [comment]
https://buomsoo-kim.github.io/colab/2018/04/16/Importing-files-from-Google-Drive-in-Google-Colab.md/

use the above or similar links 
google search key words
"google colab reading file from drive"
